services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  ratewatch:
    build: .
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8081
      - API_KEY_SECRET=your-super-secret-key-change-this
      - RUST_LOG=info
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

volumes:
  redis_data:
