apiVersion: v1
kind: Secret
metadata:
  name: ratewatch-secrets
  namespace: ratewatch
type: Opaque
data:
  # Base64 encoded values - update these with your actual secrets
  # echo -n "your-secret-key-here" | base64
  API_KEY_SECRET: Y2hhbmdlLXRoaXMtdG8tYS1zZWN1cmUtcmFuZG9tLXN0cmluZy1taW5pbXVtLTMyLWNoYXJhY3RlcnM=
  REDIS_PASSWORD: ""