apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ratewatch-metrics
  namespace: ratewatch
  labels:
    app: ratewatch
spec:
  selector:
    matchLabels:
      app: ratewatch
      component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s